version: '3.8'

services:
  frontend: 
    image: python:3.9
    command: python -m http.server 3030 --bind 0.0.0.0
    ports:
      - "3030:3030"
    volumes:
      - .:/app  
    working_dir: /app

  cors-proxy:
    image: ghcr.io/rob--w/cors-anywhere
    container_name: cors-anywhere
    environment:
      - CORSANYWHERE_ALLOW_ORIGIN=*
      - CORSANYWHERE_DISABLE_HEADERS=origin,x-forwarded-for
    ports:
      - "8081:8080"
    
