services:
  frontend:
    image: nginx:alpine
    ports:
      - "3030:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    
