services:
  frontend:
    image: nginx:alpine
    ports:
      - "3030:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    
