services:
  frontend:
    build: .
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared-network

networks:
  shared-network:
    external: true